### ISSUE TITLE
Missing file for require in cryptocompare 0.6.0

### ISSUE THREAD

**Issue by ericbeland** [alexanderdavidpan/cryptocompare#1]
irb(main):001:0> require 'cryptocompare'
LoadError: cannot load such file -- /Users/ebeland/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cryptocompare-0.6.0/lib/cryptocompare/histo_day

**Comment by alexanderdavidpan** [comment]
@ericbeland I realized that this was due to a bad gem build. I just pushed version 0.8.0, which should be working.
