### ISSUE TITLE
Does Not Accet API_KEY parameter

### ISSUE THREAD

**Issue by neymarsabin** [alexanderdavidpan/cryptocompare#12]
My first question is how do I send API_KEY in the methods?
I tried:
`
CryptoCompare::Price.full('LTC', 'USD', { api_key: 'API_KEY' })
`
`
CryptoCompare::Price.full('LTC', 'USD', api_key: 'API_KEY')
`
Both of these methods does not accept api_key and I ended up requesting via URL on my own without using gem.

**Comment by alexanderdavidpan** [comment]
@neymarsabin this issue is being worked on in this PR: https://github.com/alexanderdavidpan/cryptocompare/pull/13

**Comment by alexanderdavidpan** [comment]
I've added this feature here: https://github.com/alexanderdavidpan/cryptocompare/pull/20

**Comment by alexanderdavidpan** [comment]
This has been added here: https://github.com/alexanderdavidpan/cryptocompare/pull/20
