### ISSUE TITLE
Coinlist

### ISSUE THREAD

**Issue by Svashta** [alexanderdavidpan/cryptocompare#2]
Is there any reason why coinlist is not included? Would you consider to add it? Thx

**Comment by alexanderdavidpan** [comment]
No reason. I will work on it this weekend and release it in the 0.12.0 version sometime this Monday (November 13, 12017)!

**Comment by Svashta** [comment]
Great, no need to rush though. I was just asking :).
But if you have time and will, why not 👍

**Comment by alexanderdavidpan** [comment]
Hi @Svashta, I have just released [cryptocompare gem v0.12.0](https://rubygems.org/gems/cryptocompare/versions/0.12.0). This version now has the method `Cryptocompare::CoinList.all`, which will return Cryptocompare's CoinList from their API.

**Comment by Svashta** [comment]
Hey @alexanderdavidpan , great news! WIll try it out. Thx!
