### ISSUE TITLE
Isolating response data

### ISSUE THREAD

**Issue by lenoxramsey** [alexanderdavidpan/cryptocompare#3]
I'm trying to isolate parts of the response data when using 
`Cryptocompare::Price.full('BTC', 'USD')`

For example, when I try to pull the market cap data from the response it won't let me do it. I've tried it a number of ways but I'm having no luck.

**Comment by alexanderdavidpan** [comment]
I don't understand what you mean.

The cryptocompare gem doesn't do any response transformation, so using `Cryptocompare::Price.full('BTC', 'USD')` is the equivalent of doing a HTTP GET request to https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC&tsyms=USD.

If you want to pull the market cap data from the response, access the `"MKTCAP"` key in the raw response like so:
```
resp = Cryptocompare::Price.full('BTC', 'USD')
resp["RAW"]["BTC"]["USD"]["MKTCAP"]
```

Or if you want to access the `"MKTCAP"` key in the display response, just do this:
```
resp = Cryptocompare::Price.full('BTC', 'USD')
resp["DISPLAY"]["BTC"]["USD"]["MKTCAP"]
```
