### ISSUE TITLE
what does LASTVOLUMETO mean?

### ISSUE THREAD

**Issue by Fuzzyma** [alexanderdavidpan/cryptocompare#4]
The title is the question :)
> what does LASTVOLUMETO mean?

Whats the difference between VOLUME and VOLUMETO?

**Comment by vcealicu** [comment]
Hello Fuzzyma,
Let's say you are looking at the BTC-USD pair,
the VOLUMEFROM is in BTC and the VOLUMETO is the volume in USD. You could divide the two and get the average price over the period.

**Comment by Fuzzyma** [comment]
Thank you very much!
