### ISSUE TITLE
www.cryptocompare.com should move to min-api.cryptocompare.com

### ISSUE THREAD

**Issue by anuaimi** [alexanderdavidpan/cryptocompare#5]
Looks like CryptoCompare is moving their API from www to min-api.   When I make API calls, the response has the following message

```
"Message"=>"This api will soon move to mi-api path.",
```

Also, the API docs reference the same information
https://www.cryptocompare.com/api/#-api-data-coinlist-

**Comment by alexanderdavidpan** [comment]
@anuaimi  I took a look at the code and it seems like only the Cryptocompare::CoinSnapshot module is not using the min-api path. I will update the code and release a new version of the gem next Monday (January 1, 2018)!

**Comment by alexanderdavidpan** [comment]
It seems like the CoinSnapshot endpoint in Cryptocompare does not yet support the min-api subdomain..._yet_.  

https://min-api.cryptocompare.com/api/data/coinsnapshot/?fsym=BTC&tsym=USD

Response:
```
{
    Response: "Error",
    Message: "",
    Type: 1,
    Aggregated: false,
    Data: [ ],
    Path: "/api/data/coinsnapshot/",
    ErrorsSummary: "Not implemented"
}
```

I will keep this issue open to keep an eye on it and close it once it is implemented by Cryptocompare.

**Comment by logicminds** [comment]
`coins = Cryptocompare::CoinList.all`

=> "Coin list succesfully returned! This api is moving to https://min-api.cryptocompare.com/data/all/coinlist, please change the path."

**Comment by alexanderdavidpan** [comment]
Closing because endpoint is still not migrated to the min-api path on CryptoCompare's API.
