### ISSUE TITLE
Cryptocompare::Exchanges.all doesnt work

### ISSUE THREAD

**Issue by cristianfervas1992** [alexanderdavidpan/cryptocompare#7]
HI i tried to do Cryptocompare::Exchanges.all but there is no JSON response :/

**Comment by alexanderdavidpan** [comment]
@cristianfervas1992 I just tried it on my machine and it works for me. What is your cryptocompare gem version? This was a feature added to v0.13.0, which is the latest version to date.

**Comment by cristianfervas1992** [comment]
@alexanderdavidpan you're totally right, I was using v0.12.0, my mistake, thanks a lot men!
